# forrás (nasznagy) | cél (naszika /volume1/homes/<user>/Drive)
/volume1/homes/andrea.tundik/Drive|/volume1/homes/andrea.tundik/Drive
/volume1/homes/laszlo.filep/Drive|/volume1/homes/laszlo.filep/Drive
/volume1/homes/sitkeitamas/Drive|/volume1/homes/sitkeitamas/Drive
/volume1/homes/tamas.sitkei/Drive|/volume1/homes/tamas.sitkei/Drive
/volume1/homes/zsofia.sitkei/Drive|/volume1/homes/zsofia.sitkei/Drive
