# forrás (nasznagy) | cél (naszika — NetBackup, sitkeitamas tulajdon)
/volume1/homes/andrea.tundik/Drive|/volume1/NetBackup/homes/andrea.tundik
/volume1/homes/laszlo.filep/Drive|/volume1/NetBackup/homes/laszlo.filep
/volume1/homes/sitkeitamas/Drive|/volume1/NetBackup/homes/sitkeitamas
/volume1/homes/tamas.sitkei/Drive|/volume1/NetBackup/homes/tamas.sitkei
/volume1/homes/zsofia.sitkei/Drive|/volume1/NetBackup/homes/zsofia.sitkei
/volume1/homes/tamas.sitkei.jr/Drive|/volume1/NetBackup/homes/tamas.sitkei.jr
